---
- name: Run RedHat stuff
  ansible.builtin.include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Run Debian Stuff
  ansible.builtin.include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Create kibana.service.d override directory
  file:
    path: /etc/systemd/system/kibana.service.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy specific Kibana Systemd override file (for pid dir)
  ansible.builtin.template:
    src: "systemd/kibana.service.j2"
    dest: "/etc/systemd/system/kibana.service"
    mode: "644"
    force: true
  notify:
    - Reload systemd configuration
    - Restart kibana

- name: Copy specific Kibana Systemd override file (for pid dir)
  ansible.builtin.template:
    src: "systemd/override.conf.j2"
    dest: /etc/systemd/system/kibana.service.d/override.conf
    mode: "644"
    force: true
  notify:
    - Reload systemd configuration
    - Restart kibana

- name: Ensure Kibana is started and enabled at boot.
  ansible.builtin.service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  ansible.builtin.template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart kibana
